name: Alkaid Lib Publish

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '#Skip')"
    steps:
      - uses: actions/checkout@v3

  publish:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '#Publish')"
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (build)
        run: ./gradlew build -x test

      - name: Build with Gradle (publish)
        run: ./gradlew publish
        env:
          REPOSITORY_ROOT_URL: ${{ secrets.REPOSITORY_ROOT_URL }}
          REPOSITORY_USER: ${{ secrets.REPOSITORY_USER }}
          REPOSITORY_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}